apps/admin/videos/urls.py
from django.conf.urls import url
from django.views.generic import ListView

from apps.admin.videos import views
from apps.admin.videos.models import Video

urlpatterns = [
    url(r'^add$', views.CreateVideo.as_view(),
        name="add_video"),
    url(r'^list$', ListView.as_view(model=Video, template_name="videos/list.html"),
        name="video_list"),
    url(r'^delete/(?P<pk>\d+)', views.VideoDelete.as_view(), name='video_delete'),

]

video_streaming/urls.py
from django.conf import settings
from django.conf.urls import include, patterns, url


urlpatterns = [
    url(r'^admin/videos/', include('apps.admin.videos.urls'),name='videos'),
    url(r'^admin/categories/', include('apps.admin.categories.urls')),
    url(r'^admin/dashboard/', include('apps.admin.dashboard.urls'), name='dashboards'),
    url(r'^auth/', include('apps.auth_user.urls'), name='auth_user'),
    url(r'^select2/', include('select2.urls')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

apps/admin/videos/models.py
from django.db import models
from django_extensions.db.models import TimeStampedModel
from apps.admin.categories.models import Category, TitleEpisode, NameProgram

Chosen_rating = (('1', '1',),
                 ('2', '2',),
                 ('3', '3',),
                 ('4', '4',),
                 ('5', '5'))


class Video(TimeStampedModel):
    name = models.CharField(max_length=150, db_index=True)

    category = models.ForeignKey(Category, related_name='categories')
    name_program = models.ForeignKey(NameProgram, related_name='name_programs')
    title_episode = models.ForeignKey(TitleEpisode, related_name='title_episodes')

    source_video = models.URLField()
    rating = models.CharField(max_length=2, choices=Chosen_rating)

    def __unicode__(self):
        return '%s' % self.name

apps/admin/videos/forms.py
from django import forms

from  apps.admin.categories.models import NameProgram, TitleEpisode, Category
from .models import Video


class CreateVideoForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all(), to_field_name='name')
    name_program = forms.ModelChoiceField(queryset=NameProgram.objects.all(), empty_label=None)
    title_episode = forms.ModelChoiceField(queryset=TitleEpisode.objects.all(), empty_label=None)

    class Meta:
        fields = '__all__'
        model = Video

apps/admin/videos/views.py
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView, DeleteView
from braces.views import LoginRequiredMixin
from .forms import CreateVideoForm
from .models import Video


class CreateVideo(LoginRequiredMixin, CreateView):
    form_class = CreateVideoForm
    template_name = 'videos/add.html'
    success_url = reverse_lazy('video_list')
    model = Video


class VideoDelete(DeleteView):
    template_name = 'delete/confrim_delete.html'
    success_url = reverse_lazy('video_list')
    model = Video

templates/videos/add.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block box_body %}
    {#    {% if form.errors %}#}
    {#    {% for field in form %}#}
    {#        {% for error in field.errors %}#}
    {#            <div class="alert alert-danger">#}
    {#                <strong>{{ error|escape }}</strong>#}
    {#            </div>#}
    {#        {% endfor %}#}
    {#    {% endfor %}#}
    {#    {% for error in form.non_field_errors %}#}
    {#        <div class="alert alert-danger">#}
    {#            <strong>{{ error|escape }}</strong>#}
    {#        </div>#}
    {#    {% endfor %}#}
    {#{% endif %}#}
    {{ form.errors }}

    <div class="box-body">
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="box box-primary">

                <form action="{% url 'add_video' %}" method="POST">
                    {% csrf_token %}
                    <div class="box-body">
                        <label>Name</label>

                        <div class="form-group">
                            {% render_field form.name class+="form-control" placeholder+="Name" %}
                        </div>

                        <label>Source Video</label>

                        <div class="form-group">
                            {% render_field form.source_video class+="form-control" placeholder+="Source video" %}
                        </div>

                        <label>Category</label>

                        <div class="form-group">
                            {% render_field form.category class+="form-control" placeholder+="Category" %}
                        </div>
                        <label>Name Program</label>


                        <div class="form-group">
                            <select class="form-control" id="id_name_program" name="name_program">
                                <option value="" selected="selected">---------</option>
                                {% for choice in form.name_program.field.queryset %}
                                    <option value="{{ choice.pk }}"
                                            name="{{ choice.category }}">{{ choice.name }}</option>



                                {% endfor %}
                            </select>
                        </div>

                        <label>Title Episode</label>


                        <div class="form-group">
                            <select class="form-control" id="id_title_episode" name="title_episode">
                                <option value="" selected="selected">---------</option>
                                {% for choice in form.title_episode.field.queryset %}
                                    <option value="{{ choice.pk }}"
                                            name="{{ choice.name_program_id }}">{{ choice.name }}</option>


                                {% endfor %}
                            </select>
                        </div>

                        <label>Rating</label>

                        <div class="form-group">
                            {% render_field form.rating class+="form-control" placeholder+="Rating" %}
                        </div>

                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Save</button>
                        <a href="{% url 'video_list' %}" class="btn btn-danger">Back </a>

                    </div>
                </form>
            </div>
            <!-- /.box -->
        </div>
        <!-- /.row -->
    </div>

{% endblock %}


{% block js %}
    <script>
        $(function () {
            $("#id_name_program").prop('disabled', true);

            $("#id_title_episode").prop('disabled', true);

            $('#id_category').change(function () {
                $("#id_name_program").val([]);
                $('#id_name_program option').hide()

                $("#id_name_program").prop('disabled', false);

                $('#id_name_program option[name="' + this.value + '"]').show()


            });

            $('#id_name_program').change(function () {


                $("#id_title_episode").val([]);
                $('#id_title_episode option').hide()

                $("#id_title_episode").prop('disabled', false);

                $('#id_title_episode option[name="' + this.value + '"]').show()


            });
        })
    </script>
{% endblock %}

templates/videos/list.html
{% extends 'base.html' %}

{% block box_body %}
    <div class="row">
        <div class="col-md-12">
            <div>
                <div class="box-body">
                    <table class="table table-bordered">
                        <tr>
                            <th style="width: 10px">#</th>
                            <th>Name</th>
                            <th>Category</th>
                            <th>Name Program</th>
                            <th>Title Episode</th>
                            <th style="width: 40px">Rating</th>
                            <th>Action</th>
                        </tr>
                        <tr>
                            {% for i in  object_list %}
                                <td> {{ forloop.counter }}</td>
                                <td>{{ i.name }}</td>
                                <td>
                                    {{ i.category }}
                                </td>
                                <td>
                                    {{ i.name_program }}
                                </td>
                                <td>
                                    {{ i.title_episode }}
                                </td>
                                <td><span class="badge bg-red">{{ i.rating }}</span></td>
                                <td>
                                    <a href=" {% url "video_delete" i.id %}">
                                        Delete
                                    </a>

                                </td>
                                </tr>
                            {% endfor %}

                    </table>
                </div>
                <div class="box-footer clearfix">
                    <ul class="pagination pagination-sm no-margin pull-right">
                        <li><a href="#">&laquo;</a></li>
                        <li><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">&raquo;</a></li>
                    </ul>

                        <a href="{% url 'add_video' %}" class="btn btn-success">Add </a>
                </div>


            </div>
        </div>

    </div>
{% endblock %}